require "./src/crdo/types"
require "./src/crdo/when_parser"
require "./src/crdo/clock"
require "./src/crdo/system_clock"
require "./src/crdo/global_config"
require "./src/crdo/crontab_source_loader"
require "./src/crdo/crontab_verifier"
require "./src/crdo/crontab"
require "./src/crdo/task"
require "./src/crdo/task_support"
require "./src/crdo/task_process_runner"
require "./src/crdo/task_run_eligibility_evaluator"
require "./src/crdo/task_mailer"
require "./src/crdo/task_stop_handler"
require "./src/crdo/task_state"
require "./src/crdo/schedule_support"
require "./src/crdo/schedule_state_store"
require "./src/crdo/schedule_reload_planner"
require "./src/crdo/schedule_loop_controller"
require "./src/crdo/schedule_reporter"
require "./src/crdo/schedule"
require "./src/crdo/cli"

{% unless flag?(:crdo_spec) %}
main
{% end %}
